//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int ChiTietID { get; set; }
        public int HoaDonID { get; set; }
        public string MonAnID { get; set; }
        public Nullable<int> Soluong { get; set; }
        public int BanAnID { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
